In [9]:
import pandas as pd
import pandas_profiling

In [10]:
df = pd.read_csv('airbnb/AB_NYC_2019.csv')

In [11]:
df.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
24607,19785737,Hillside Hotel,134184451,Hillside Hotel,Queens,Jamaica,40.70445,-73.81399,Private room,135,1,1,2017-10-08,0.05,18,180
42734,33169890,Cozy Bedroom on Upper west near Columbia U,233917490,Yoannie,Manhattan,Upper West Side,40.80221,-73.96677,Private room,40,1,0,NaN,NaN,1,1
7101,5136673,Spacious Brooklyn Loft/private room,8118080,Theresa,Brooklyn,Bedford-Stuyvesant,40.68716,-73.91882,Private room,40,7,0,NaN,NaN,1,0
2546,1316961,Huge Sunny Apt Hip/Family Area,772862,Jesse,Brooklyn,Clinton Hill,40.68645,-73.96587,Entire home/apt,160,3,24,2019-05-18,0.33,1,365
11573,9004946,One bedroom garden apartment.,47025665,Heather,Brooklyn,Bedford-Stuyvesant,40.68973,-73.93785,Entire home/apt,105,4,131,2019-06-17,2.92,1,55
21935,17640413,"Private room & living room, one block from sub...",44709817,Jackie,Brooklyn,Bedford-Stuyvesant,40.68187,-73.94589,Private room,60,1,3,2017-12-16,0.16,1,0
1662,753687,Mitchell Manor,3964655,Nicole,Brooklyn,Bedford-Stuyvesant,40.67958,-73.93687,Entire home/apt,125,3,104,2019-06-24,1.36,1,275
8571,6599302,"An ENTIRE, Lovely NYC Apartment",15386409,Mateo,Manhattan,Harlem,40.82879,-73.93821,Entire home/apt,80,3,3,2017-08-15,0.06,1,0
25447,20356797,New York Apartment in Queens,127077398,Ming,Queens,Ozone Park,40.67801,-73.84590,Entire home/apt,110,2,51,2019-07-06,2.22,1,295
31997,24970711,Budget Basement,188783370,Faraz,Queens,Flushing,40.73968,-73.80601,Private room,80,1,9,2018-08-10,0.65,1,0

In [13]:
profile = df.profile_report(style={'full_width':True})

In [14]:
profile.to_file(output_file='airbnb/airbnb.html')